name: Check MSRV

on:
  workflow_call:
  workflow_dispatch:

jobs:
  check-msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: https://gitea.com/yuusha/js-hashfiles@v1
        id: get-hash
        with:
          patterns: |-
            **/Cargo.toml

      - name: Set up cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-check-msrv-${{ steps.get-hash.outputs.hash }}
          restore-keys: ${{ runner.os }}-cargo-check-msrv-

      - uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-msrv
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-msrv

      - name: Get current msrv
        id: data-msrv
        run: |
          current_msrv=$(cargo msrv show --output-format minimal);
          echo "current msrv: $current_msrv";
          echo "current=$current_msrv" >> "$GITHUB_OUTPUT";

      - name: Run cargo msrv
        run: cargo msrv verify --min ${{ steps.data-msrv.outputs.current }}

      - name: echo msrv info
        if: failure()
        run: |-
          echo "current msrv: ${{ steps.data-msrv.outputs.current }}";
          new_msrv=$(cargo msrv show --output-format minimal);
          echo "new msrv: $new_msrv";
