name: Crate Type

on:
  workflow_call:
    outputs:
      is_lib:
        value: ${{ jobs.check-crate-type.outputs.is_lib }}
      is_bin:
        value: ${{ jobs.check-crate-type.outputs.is_bin }}

jobs:
  check-crate-type:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: https://gitea.com/yuusha/js-hashfiles@v1
        id: get-hash
        with:
          patterns: |-
            **/Cargo.toml

      - name: Set up cargo cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-check-crate-type-${{ steps.get-hash.outputs.hash }}
          restore-keys: ${{ runner.os }}-cargo-check-crate-type-

      - name: Install jql
        uses: taiki-e/install-action@v2
        with:
          tool: jql

      - name: Searching for lib
        id: searching
        run: |
          result=$(cargo metadata --format-version=1 --no-deps | jql '"packages"|>"targets"<|[0]|>"kind"' | jql '..' -i);
          echo "targets=$result" >> "$GITHUB_OUTPUT";
          echo kind of targets $result;

    outputs:
      is_lib: ${{ contains(steps.searching.outputs.targets, 'lib') }}
      is_bin: ${{ contains(steps.searching.outputs.targets, 'bin') }}
