name: Build and Push Docker Image

on:
  push:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  REGISTRY_IMAGE: git.dimlight.eu/konkrotte/hydrus-ai-tagger

jobs:
  build-and-push:
    name: Build and Push Multi-Arch Docker Image
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        kind:
          - cpu
          - cuda

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}

      - uses: docker/metadata-action@v5
        id: metadata
        with:
          tags: type=raw,value=latest,enable={{is_default_branch}}
          images: ${{ env.REGISTRY_IMAGE }}
          flavor: prefix=${{ matrix.kind }}-

      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ${{ env.REGISTRY_IMAGE }}/cache
          cache-key: ${{ matrix.kind }}
          cache-key-fallback: cpu
          cache-type: gha

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        id: build
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          target: ${{ matrix.kind }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}

      # TODO: Fix TensorRT Docker images
      # - name: Build and push Docker image - TensorRT
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: git.dimlight.eu/konkrotte/hydrus-ai-tagger:master-tensorrt
      #     target: tensorrt
      #     platforms: linux/amd64
      #     cache-from: mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${{ env.REGISTRY_IMAGE }}:buildcache
      #     cache-to: mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${{ env.REGISTRY_IMAGE }}:buildcache,mode=max
